@echo off
color 1f
setlocal EnableDelayedExpansion
set version=v2.3
mode con cols=58 lines=30
title LEWA主题制作[移植]助手%version%
@echo ********************************************************
@echo.
@echo               LEWA主题制作[移植]助手%version%
@echo.
@echo.                                  
@echo ********************************************************
echo --------------------------------------------------------
echo .使用前最好查阅说明！
echo .请尊重作者劳动【转载请注明】
echo .请不要修改文件夹和文件名，否则工具将无法运行！
echo --------------------------------------------------------
echo 按任意键进入主菜单
pause>nul
tools\bat\menu